### ISSUE TITLE
Make a separate build line in for Sonar analysis

### ISSUE THREAD

**Issue by ohbus** [iluwatar/java-design-patterns#1875]
I have overlooked that there will be two simultaneous reports generated for Sonar issues which I have overlooked.

- [ ] Dismiss Matrix building of the project.
- [ ] We need to split into two build pipelines, one for running sonar analysis against the latest `zulu` build, and one with the latest JDK build.
- [ ] Let us use the cache feature for `maven` dependencies.

_Originally posted by @ohbus in https://github.com/iluwatar/java-design-patterns/pull/1868#pullrequestreview-785844000_
