### ISSUE TITLE
Refactor event sourcing

### ISSUE THREAD

**Issue by yongyongkr** [iluwatar/java-design-patterns#2445]
I'll refactor some codes of event sourcing pattern. The specific tasks I suggest are listed below.

- [ ] remove the use of deprecated `JsonParser`
- [ ] use jackson `ObjectMapper` instead of `Gson`
- [ ] fix some warnings checked by sonarlint
