### ISSUE TITLE
Explanation for design patterns

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#590]
We want to present the design patterns better as the current does not reach its goal of explaining how the pattern works in a simplest possible way. I'm hugely inspired by https://github.com/kamranahmedse/design-patterns-for-humans repository.

Let's do this by adding 'Explanation' section to the patterns' `README.md` file. For an example see http://java-design-patterns.com/patterns/bridge/.

Let's track the issue progress here with the following checklist that indicates the patterns where explanation section is already available.

- [x] abstract-document
- [x] abstract-factory
- [x] active-object
- [x] acyclic-visitor
- [x] adapter
- [x] aggregator-microservices
- [x] ambassador
- [x] api-gateway
- [x] arrange-act-assert
- [x] async-method-invocation
- [x] balking
- [x] bridge
- [x] builder
- [x] business-delegate
- [x] bytecode
- [x] caching
- [x] callback
- [x] chain
- [x] circuit-breaker
- [x] cloud-static-content-hosting
- [ ] collection-pipeline
- [ ] combinator
- [x] command
- [ ] commander
- [x] composite
- [x] composite-entity
- [x] converter
- [ ] cqrs
- [x] dao
- [ ] data-bus
- [ ] data-locality
- [ ] data-mapper
- [x] data-transfer-object
- [x] decorator
- [ ] delegation
- [x] dependency-injection
- [ ] dirty-flag
- [ ] double-buffer
- [ ] double-checked-locking
- [ ] double-dispatch
- [ ] eip-aggregator
- [ ] eip-message-channel
- [ ] eip-publish-subscribe
- [ ] eip-splitter
- [ ] eip-wire-tap
- [ ] event-aggregator
- [ ] event-based-asynchronous
- [ ] event-driven-architecture
- [ ] event-queue
- [ ] event-sourcing
- [x] execute-around
- [ ] extension-objects
- [x] facade
- [x] factory
- [ ] factory-kit
- [x] factory-method
- [ ] fan-out-fan-in
- [ ] feature-toggle
- [x] filterer
- [x] fluentinterface
- [ ] flux
- [x] flyweight
- [ ] front-controller
- [x] game-loop
- [ ] guarded-suspension
- [ ] half-sync-half-async
- [ ] hexagonal
- [ ] intercepting-filter
- [x] interpreter
- [x] iterator
- [x] layers
- [ ] lazy-loading
- [ ] leader-election
- [ ] leader-followers
- [x] lockable-object
- [ ] marker-interface
- [ ] master-worker
- [x] mediator
- [x] memento
- [ ] model-view-controller
- [ ] model-view-presenter
- [x] model-view-viewmodel
- [ ] module
- [ ] monad
- [ ] monostate
- [x] multiton
- [ ] mute-idiom
- [ ] naked-objects
- [x] null-object
- [ ] object-mother
- [x] object-pool
- [x] observer
- [ ] page-object
- [x] parameter-object
- [ ] partial-response
- [x] pipeline
- [x] poison-pill
- [x] presentation-model
- [x] priority-queue
- [x] private-class-data
- [ ] producer-consumer
- [x] promise
- [ ] property
- [x] prototype
- [x] proxy
- [ ] queue-based-load-leveling
- [ ] reactor
- [ ] reader-writer-lock
- [x] registry
- [x] repository
- [ ] resource-acquisition-is-initialization
- [x] retry
- [ ] role-object
- [ ] saga
- [ ] semaphore
- [x] separated-interface
- [ ] servant
- [ ] serverless
- [ ] service-layer
- [ ] service-locator
- [ ] sharding
- [x] singleton
- [x] spatial-partition
- [x] special-case
- [x] specification
- [x] state
- [ ] step-builder
- [ ] strangler
- [x] strategy
- [ ] subclass-sandbox
- [x] table-module
- [x] template-method
- [x] thread-pool
- [x] throttling
- [ ] thread-local-storage
- [x] tolerant-reader
- [x] trampoline
- [x] transaction-script
- [x] twin
- [ ] type-object
- [x] unit-of-work
- [ ] update-method
- [ ] value-object
- [x] version-number
- [x] visitor

**Comment by iluwatar** [comment]
Changed https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template a bit. There is no diagram anymore. Explanation section was added.

**Comment by iluwatar** [comment]
Issue moved to https://github.com/iluwatar/java-design-patterns-web/issues/5

**Comment by pshirley** [comment]
:@iluwatar OK if I work on an explanation for Mediator?

**Comment by iluwatar** [comment]
Thanks @pshirley go ahead. Your contribution is warmly welcome!

**Comment by vINCENT8888801** [comment]
Hello, I referred to your other explanation and come up with this private data class explanation. Would love to have some comment and advice. #1482

**Comment by kanwarpreet25** [comment]
Is it available ?

**Comment by iluwatar** [comment]
Yes @kanwarpreet25 which pattern do you want to work on?

**Comment by kanwarpreet25** [comment]
@iluwatar  visitor pattern

**Comment by iluwatar** [comment]
@kanwarpreet25 I think it's already in quite good shape. See https://java-design-patterns.com/patterns/visitor/ What aspects would you improve?

**Comment by AJESH-CR** [comment]
Can I start working on this?. Didn't see anyone assigned to this task. @iluwatar @ohbus

**Comment by ohbus** [comment]
> Can I start working on this?. Didn't see anyone assigned to this task. @iluwatar @ohbus

As this is a continuous effort please feel free to make contributions on the same.

**Comment by AJESH-CR** [comment]
Sounds good @ohbus. Does anyone working on collection-pipeline ?

**Comment by iluwatar** [comment]
I don't think so, please go ahead @AJESH-CR

**Comment by QihaMarz** [comment]
May I start working on event-driven-architecture ? @ohbus @iluwatar

**Comment by ohbus** [comment]
> May I start working on event-driven-architecture ? @ohbus @iluwatar

Sure thing! Please go ahead!!

**Comment by Ln11211** [comment]
@ohbus, just wondering where can I find the explanations like "https://github.com/kamranahmedse/design-patterns-for-humans" for the above mentioned topics(that are done), coz I might find some useful when I learn them...

**Comment by ohbus** [comment]
> @ohbus, just wondering where can I find the explanations like "https://github.com/kamranahmedse/design-patterns-for-humans" for the above mentioned topics(that are done), coz I might find some useful when I learn them...

More than finding this is about how you would like to explain in simple words what you have understood already.

This is about connecting trivial things that we interact with daily and explaining them in your own way.

**Comment by QihaMarz** [comment]
I've already done all the explanations part but I haven't got to create the programmatic example. Should I continue doing it? since it will take a long time for me to create the right codes. Thank you :)

**Comment by ohbus** [comment]
> I've already done all the explanations part but I haven't got to create the programmatic example. Should I continue doing it? since it will take a long time for me to create the right codes. Thank you :)

The programmatic examples are already done unless you are implementing a pattern that is yet to be included in this repository.

**Comment by AJESH-CR** [comment]
@iluwatar @ohbus The Changes are ready to review.

**Comment by QihaMarz** [comment]
@iluwatar @ohbus The updates for explanation is ready to review.

**Comment by dmdbilal** [comment]
I've made the pull request but it fails in 1 test and I'm a beginner to open source. Can someone explain why I'm failed in that test.
Test:
if [ -n "${CIRCLE_PR_NUMBER}" ]; then MAVEN_OPTS="-Xmx3000m" xvfb-run ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \ -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} \ -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} \ -Dsonar.pullrequest.base=master else echo "No Sonar PR analysis as this is not a pull request" fi

**Comment by iluwatar** [comment]
@ohbus could you take a look at this ^

**Comment by JanFidor** [comment]
@iluwatar could I work on delegation?

**Comment by iluwatar** [comment]
Sure, go ahead @JanFidor

**Comment by ChenQixiangZzz** [comment]
@iluwatar @ohbus May I work on the subclass-sandbox?

**Comment by murphShaw** [comment]
@iluwatar Can I please contribute to the factory-kit?

**Comment by annieS987** [comment]
@iluwatar Can I work on the role-object part? Cheers.

**Comment by iluwatar** [comment]
Excellent, go ahead @murphShaw @SammanPali @murphShaw @annieS987

**Comment by u7281975** [comment]
@iluwatar Hello, can I be assigned the data-bus design pattern?

**Comment by iluwatar** [comment]
Ok @u7281975

**Comment by steph88ss** [comment]
@iluwatar Hi, can I be assigned the reader-writer-lock pattern?

**Comment by XianWu99** [comment]
@iluwatar Hi, can I be assigned to the data-mapper design pattern?

**Comment by iluwatar** [comment]
Github doesn't allow me to add any more assignees, but consider yourselves hired @steph88ss and @XianWu99

**Comment by iluwatar** [comment]
@shubhig226 please mention the pattern you'd like to work on

**Comment by ManviGoel26** [comment]
@iluwatar Can I please work on Producer-Consumer?

**Comment by iluwatar** [comment]
Sure, go ahead @ManviGoel26

**Comment by iluwatar** [comment]
I have split up this issue into multiple independent ones e.g. "Explanation for Bridge". If you are working on some explanation, please comment on the new issue and I'll assign it to you. I'll close this task now.
